# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2e936f40257061a97a05d61876456016549c4678541c4fd55ee569f5d419f03629c7f49caf20fcc6a6eef6b1dc9b1095c6001e3fa98cd3ce7a47a30f4e732e

test:
  secret_key_base: 2854513cb2e2a91563c9c605d85ff9ce3cbd22f4adf0907c29167b5b592a282162b95f89f11fed1e9c8f4aa9f14f762dc9e1f7f02e18c9d988a5e6cc510199fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
